---
title: "Carômetro"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Esse app foi construído usando o <a href="http://www.r-project.org/" target="_blank">R</a> e <a href="http://shiny.rstudio.com/" target="_blank">Shiny</a>.

## Sobre o aplicativo

O objetivo do aplicativo foi explorar os dados da votação do impeachment na câmara e as declarações parciais que se sabia até o momento. As informações não estão mais atualizadas mas estou distribuindo o aplicativo como está.

O aplicativo conta atualmente com o recurso de filtragem de deputados de acordo com a orientação de voto no impeachment. O ideal, se alguém tiver a disponibilidade, seria submeter um pull request com a informação atualizada.

## Como contribuir

Faça um [fork](https://github.com/flaviobarros/carometro#fork-destination-box) e submeta um [pull request](https://github.com/flaviobarros/carometro/pull/new/master). Se você pretende utilizar algum código deste app, fique a vontade, mas **cite a fonte**. Qualquer dúvida com relação ao uso do app, a como contribuir ou para relatar problemas, use os [issues](https://github.com/flaviobarros/carometro/issues) do Github.

## Autor
Meu nome é Flavio Barros, sou Estatístico e escrevo regularmente no meu blog, o [R Mining](www.rmining.net).  
